interface Member {
	name: string;
	title: string;
	desc: string;

	avatarType: "github" | "qq" | "url";
	avatar: string;
	birthYear: string;

	github: string;
	website: string;

	feed: string | null;
}

export const members: Member[] = [
	{
		name: "纸鹿",
		title: "Zhilu",
		desc: "纸鹿至麓不知路，支炉制露不止漉",
		avatarType: "github",
		avatar: "L33Z22L11",
		birthYear: "2003",
		github: "L33Z22L11",
		website: "https://blog.zhilu.cyou/",
		feed: "https://blog.zhilu.cyou/atom.xml",
	},
	{
		name: "浮杨",
		title: "浮🐑",
		desc: "On the other side of obstacles",
		avatarType: "github",
		avatar: "FloatSheep",
		birthYear: "2010",
		github: "FloatSheep",
		website: "https://blog.hesiy.cn/",
		feed: "https://blog.hesiy.cn/posts/index.xml",
	},
	{
		name: "春华秋实",
		title: "GitHub Org. Maintainer",
		desc: "man what can i say",
		avatarType: "github",
		avatar: "chun-awa",
		birthYear: "2009",
		github: "chun-awa",
		website: "https://chun-awa.github.io/blog/",
		feed: null,
	},
	{
		name: "葱苓",
		title: "葱苓sama",
		desc: "Don't worry, be happy.",
		avatarType: "qq",
		avatar: "1298926752",
		birthYear: "1998",
		github: "ciraos",
		website: "https://blog.ciraos.top/",
		feed: null,
	},
	{
		name: "liushen",
		title: "群混子",
		desc: "柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜",
		avatarType: "qq",
		avatar: "3162475700",
		birthYear: "2003",
		github: "willow-god",
		website: "https://www.liushen.fun/",
		feed: "https://blog.liushen.fun/atom.xml",
	},
	{
		name: "Marcus",
		title: "马库斯",
		desc: "人间值得，未来可期",
		avatarType: "github",
		avatar: "marcus-zh",
		birthYear: "2009",
		github: "Marcus-zh",
		website: "https://blog.marcus233.top/",
		feed: "https://blog.marcus233.top/atom.xml",
	},
	{
		name: "mio",
		title: "蓝白碗",
		desc: "白驹过隙 忽然而已",
		avatarType: "qq",
		avatar: "3085438886",
		birthYear: "2006",
		github: "pzjawa",
		website: "https://pzj.us.kg/",
		feed: "https://blog.pzj.us.kg/atom.xml",
	},
	{
		name: "陈鑫磊",
		title: "cxl2020mc",
		desc: "当你能做出选择的时候，不要让自己后悔",
		avatarType: "qq",
		avatar: "1176503930",
		birthYear: "2008",
		github: "cxl2020MC",
		website: "https://blog.cxl2020mc.top/",
		feed: "https://blog.cxl2020mc.top/atom.xml",
	},
	{
		name: "Redish101",
		title: "数据库",
		desc: null,
		avatarType: "qq",
		avatar: "3974549032",
		birthYear: "2010",
		github: "Redish101",
		website: "https://redish101.top/",
		feed: "https://blog.redish101.top/feed",
	},
	{
		name: "Ariasaka",
		title: "嘟嘟嘟",
		desc: "人有悲欢离合 月有阴晴圆缺",
		avatarType: "qq",
		avatar: "2192016328",
		birthYear: "2010",
		github: "LYXOfficial",
		website: "https://blog.yaria.top/",
		feed: "https://blog.yaria.top/feed",
	},
	{
		name: "eastwind",
		title: "EW",
		desc: "东风不与周郎便",
		avatarType: "github",
		avatar: "WindyDante",
		birthYear: "2004",
		github: "WindyDante",
		website: "https://996.windydante.top/",
		feed: null,
	},
	{
		name: "天翔TNXG",
		title: "iykrzu",
		desc: "明日尚未到来，希望凝于心上",
		avatarType: "qq",
		avatar: "2271225249",
		birthYear: "2007",
		github: "TNXG",
		website: "https://tnxg.top/",
		feed: "https://tnxgmoe.com/feed",
	},
	{
		name: "Q78KG",
		title: "星野梦月",
		desc: "星屑落肩缓拾光，梦羽临窗静听风",
		avatarType: "github",
		avatar: "Hoshino-Yumetsuki",
		birthYear: "????",
		github: "Hoshino-Yumetsuki",
		website: "https://yumetsuki.moe/",
		feed: "https://yumetsuki.moe/atom.xml",
	},
	{
		name: "Fgaoxing",
		title: "大废物",
		desc: "I'm a teenager who loves technology.",
		avatarType: "github",
		avatar: "Fgaoxing",
		birthYear: "20xx",
		github: "Fgaoxing",
		website: "https://www.yt-blog.top/",
		feed: "https://www.yt-blog.top/atom.xml",
	},
	{
		name: "Chinyuan Tai",
		title: "kd",
		desc: "LOVE&PEACE ",
		avatarType: "github",
		avatar: "Kindle-deep",
		birthYear: "2009",
		github: "Kindle-deep",
		website: "https://www.knlde.top/",
		feed: "https://www.knlde.top/index.xml",
	},
	{
		name: "taosu",
		title: "FATA Home",
		desc: "Daily Growing",
		avatarType: "qq",
		avatar: "2412211487",
		birthYear: "2004",
		github: "taosu0216",
		website: "https://yblue.top/",
		feed: null,
	},
	{
		name: "皓然",
		title: "Horon",
		desc: "分享生活和技术的点滴",
		avatarType: "qq",
		avatar: "1269024821",
		birthYear: "2003",
		github: "HoronLee",
		website: "https://blog.horonlee.com/",
		feed: "https://blog.horonlee.com/atom.xml",
	},
];
